### ISSUE TITLE
请问一下部署好了后如何使用呢？

### ISSUE THREAD

**Issue by sky22333** [bboysoulcn/registry-mirror#1]
```
root@1:~# docker pull http://公网IP:5000/mysql:5.7
invalid reference format
root@1:~# docker pull http://公网IP:5000/library/mysql:5.7
invalid reference format
root@1:~# docker pull 公网IP:5000/mysql:5.7
Error response from daemon: Get "https://公网IP:5000/v2/": http: server gave HTTP response to HTTPS client
root@1:~# docker pull http://公网IP:5000/mysql:5.7
invalid reference format
root@1:~# 
```

####  无法使用

**Comment by helloord** [comment]
> ```
> root@1:~# docker pull http://公网IP:5000/mysql:5.7
> invalid reference format
> root@1:~# docker pull http://公网IP:5000/library/mysql:5.7
> invalid reference format
> root@1:~# docker pull 公网IP:5000/mysql:5.7
> Error response from daemon: Get "https://公网IP:5000/v2/": http: server gave HTTP response to HTTPS client
> root@1:~# docker pull http://公网IP:5000/mysql:5.7
> invalid reference format
> root@1:~# 
> ```
> 
> #### 无法使用

cat /etc/docker/daemon.json
{
	"insecure-registries":["registry.gddi.com", "hub.gddi.com","10.11.0.205:5000"],
        "registry-mirrors": [
	  "http://192.168.1.33:5000"
        ],

**Comment by helloord** [comment]
> ```
> root@1:~# docker pull http://公网IP:5000/mysql:5.7
> invalid reference format
> root@1:~# docker pull http://公网IP:5000/library/mysql:5.7
> invalid reference format
> root@1:~# docker pull 公网IP:5000/mysql:5.7
> Error response from daemon: Get "https://公网IP:5000/v2/": http: server gave HTTP response to HTTPS client
> root@1:~# docker pull http://公网IP:5000/mysql:5.7
> invalid reference format
> root@1:~# 
> ```
> 
> #### 无法使用

cat /etc/docker/daemon.json
{
        "registry-mirrors": [
	  "http://ip:5000"
        ]
}
