### ISSUE TITLE
服务的作用

### ISSUE THREAD

**Issue by wuhunyu** [bboysoulcn/registry-mirror#2]
弱弱问一下

- 这个服务要部署在一台可以访问外网以及可以被国内访问的机器上，完全充当一个中转（类似于机场）一样的作用
- 服务会把中转过程中拉取的镜像缓存在本地，并定期清理
- 代理服务暴露的访问地址必须要配置 https，不然不被 docker 客户端认可

这样理解对吗

**Comment by bboysoulcn** [comment]
> 弱弱问一下
> 
> * 这个服务要部署在一台可以访问外网以及可以被国内访问的机器上，完全充当一个中转（类似于机场）一样的作用
> * 服务会把中转过程中拉取的镜像缓存在本地，并定期清理
> * 代理服务暴露的访问地址必须要配置 https，不然不被 docker 客户端认可
> 
> 这样理解对吗

对
