### ISSUE TITLE
请教一个docker使用上的小问题

### ISSUE THREAD

**Issue by owo10086** [bboysoulcn/registry-mirror#5]
我拉取这样的命令docker pull docker.****.xyz/nginx:latest

就提示：Error response from daemon: manifest for docker.****.com/nginx:latest not found: manifest unknown: manifest unknown

然后拉取这样的就可以：docker pull docker.****.xyz/linuxserver/nginx

**Comment by bboysoulcn** [comment]
docker pull docker.****.xyz/library/nginx:latest
